### ISSUE TITLE
LWMA Algoritm Diff

### ISSUE THREAD

**Issue by vitorgamer58** [cryptoluka/CryptoLuKa#10]
Is there any plan by LUKA to change the difficulty algorithm to avoid Hash attacks? is a general trend in the cryptonight currencies of making a fork and switching to the LWMA algorithm, it works to calculate the approximate HashRate and estimate the difficulty of the next block according to the weighted average harmonic, so that the difficulty and hash of the blocks recent has a larger weight than the older blocks within the update window.
Refer to https://github.com/zawy12/difficulty-algorithms/issues/3 and https://github.com/seredat/karbowanec/issues/29

Example: https://github.com/wownero/wownero/pull/1/commits/efe03eb0379d87d521f6fc86cef39ec06c119f41

Implemented In:
https://github.com/niobio-cash/niobio-node-daemon/commit/27b9c1a0c3ae95527f69131a3c21bb81028c385c
https://github.com/forknote/forknote/commit/0a686c873cb94fff857b64af8af704ca38d71534
https://github.com/masari-project/masari/issues/5
https://github.com/havenprotocol/haven/issues/3
https://github.com/ipbc-dev/ipbc/commit/20b57f904fb6604b6d6d7f662c27bfca7c5a06f0
https://github.com/sumoprojects/sumokoin/issues/41

**Comment by cryptoluka** [comment]
#12 Implemented!

**Comment by vitorgamer58** [comment]
TOP DEMAIS
