### ISSUE TITLE
wallet y windows

### ISSUE THREAD

**Issue by rgcl** [cryptoluka/CryptoLuKa#14]
Hola, por curiosear descargué la wallet y a diferencia de litecoin se pone como loco altiro a descargar los gigas de los bloques en no sé donde (las otras wallet te preguntan primero en donde descargarlos).

Dónde se descargan?

**Comment by cryptoluka** [comment]
En la carpeta por defecto para aplicaciones windows %appdata% -> Roaming\Luka
Para unix es en -> ~/.Luka
