### ISSUE TITLE
error al compilar en ubuntu 16.04

### ISSUE THREAD

**Issue by unratedCL** [cryptoluka/CryptoLuKa#3]
$ apt-get update OK
$ apt-get upgrade OK
$ apt-get install qtbase5-dev libssl-dev cmake git libboost1.58-all-dev build-essential g++ OK
$ git clone https://github.com/cryptoluka/cryptoluka OK
$ cd cryptoluka/ OK
$ cmake CMakeLists.txt OK
$ make install -j 2 OK
$ cd cryptonote/ OK
$ make install -j 2 > **ERROR : "make: *** No rule to make target 'install'.  Stop."**

**Comment by unratedCL** [comment]
lo solucione de la siguiente forma:

$ cd cryptonote/
$ cmake CMakeLists.txt
$ cd src/
$ make

posteriormente correr lukad

**Comment by rigoy22k** [comment]
en el list ya está cryptonote comp.
