### ISSUE TITLE
¿Existe una guía para Centos 7?

### ISSUE THREAD

**Issue by magentochile** [cryptoluka/CryptoLuKa#5]
Estimados,

Traté de seguir su guía adaptando los comandos para Centos 7. Pero tengo el siguiente error (estoy en un servidor de pruebas 4G RAM, para luego una vez depurado, pasarlo a un servidor de 8G RAM):

[root@centos-s-2vcpu-4gb-nyc1-01 cryptoluka]# cmake CMakeLists.txt
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1753 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.53.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.58 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:43 (find_package)

-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Success
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER - Success
-- Performing Test HAVE_FALLOCATE
-- Performing Test HAVE_FALLOCATE - Success
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - found
-- JNI library is disabled
-- Configuring incomplete, errors occurred!
See also "/root/cryptoluka/CMakeFiles/CMakeOutput.log".
See also "/root/cryptoluka/CMakeFiles/CMakeError.log".

¿Alguna ayuda para poder arrancarlo en Centos 7?

Saludos y gracias!!!

P.S: Mañana seguiré intentando!

**Comment by cryptoluka** [comment]
--- Detected version of Boost is too old. Requested version was 1.58 (or
newer).

Tienes boost 1.53 en tu servidor, debes instalar a lo menos 1.58

**Comment by magentochile** [comment]
Oka cryptoluka!!! muchas gracias... voy a tratar de modificar a boost 1.58. De todas maneras lo haré en ubuntu 16.04.4 y en Centos 7 para ir comparando. Lo ideal además podrían sacar una versión para Docker.

Por otro lado, muchas felicitaciones!!! estoy realmente sorprendido del desarrollo que han realizado, les he revisado minuciosamente su desarrollo en estos pocos días, más su wallet con minero incluido... muy bien! Por el momento he estado trabajando con Parity para Ethereum, y su desarrollo con Crypto Luka está en muy buen nivel... creo que su moneda será muy bien cotizada... el desarrollo que han realizado se ve robusto. Creo que pronto agregaré su moneda Crypto Luka y Ethereum como método de pago en nuestra web (aún analizo la forma, no sé si con un contrato inteligente o un simple método de pago con la dirección wallet, o algo con web3... aún estoy entre desarrollos).

Saludos y felicitaciones desde Magento Chile!
